version: "3.3"
services:
  logs-API:
    build: .
    restart: always
    network_mode: "host"
    privileged: true
    container_name: logs-API
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "production_status"
        env: "os"
    labels:
      production_status: "release"
    environment:
      - os=debian
    volumes:
      - /root/vakilbashi/logsAPI:/usr/src/app